'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlyEduDownloader.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 {\rtf1\ansi\ansicpg936\deff0\deflang1033\deflangfe2052{\fonttbl{\f0\fnil\fcharset134 \&apos;ce\&apos;a2\&apos;c8\&apos;ed\&apos;d1\&apos;c5\&apos;ba\&apos;da;}}
        '''{\colortbl ;\red255\green0\blue0;\red0\green0\blue255;}
        '''{\*\generator Msftedit 5.41.21.2512;}\viewkind4\uc1\pard\qc\lang2052\f0\fs36\&apos;c3\&apos;e2\&apos;d4\&apos;f0\&apos;c9\&apos;f9\&apos;c3\&apos;f7\fs18\par
        '''\pard\fs20 1.\&apos;b1\&apos;be\&apos;c8\&apos;ed\&apos;bc\&apos;fe\&apos;cd\&apos;ea\&apos;c8\&apos;ab\&apos;c3\&apos;e2\&apos;b7\&apos;d1\&apos;a3\&apos;ac\&apos;bd\&apos;f6\&apos;d3\&apos;c3\&apos;d3\&apos;da\&apos;d1\&apos;a7\&apos;cf\&apos;b0\&apos;ba\&apos;cd\&apos;d1\&apos;d0\&apos;be\&apos;bf\&apos;d6\&apos;c7\&apos;bb\&apos;db\&apos;d6\&apos;d0\&apos;d0\&apos;a1\&apos;d1\&apos;a7\&apos;b7\&apos;fe\&apos;ce\&apos;f1\&apos;d4\&apos;ad\&apos;c0\&apos;ed\ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property license() As String
            Get
                Return ResourceManager.GetString("license", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
