'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlyEduDownloader.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 main_feddev
        ''' 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AppBuildBranch() As String
            Get
                Return ResourceManager.GetString("AppBuildBranch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 main_feddev.250316-1839
        ''' 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AppBuildChannel() As String
            Get
                Return ResourceManager.GetString("AppBuildChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/feedbacklink.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property IssueA() As String
            Get
                Return ResourceManager.GetString("IssueA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://github.com/cjhdevact/FlyEduDownloader/issues 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property IssueG() As String
            Get
                Return ResourceManager.GetString("IssueG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/feedbacklink.html 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property IssueT() As String
            Get
                Return ResourceManager.GetString("IssueT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {\rtf1\adeflang1025\ansi\ansicpg936\uc2\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe2052\themelang1033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        '''{\f36\fbidi \fnil\fcharset134\fprq2{\*\panose 02010600030101010101}\&apos;b5\&apos;c8\&apos;cf\&apos;df{\*\falt DengXian};}{\f44\fbidi \fswiss\fcharset134\fprq2{\*\panose 000000000000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property license() As String
            Get
                Return ResourceManager.GetString("license", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/noticemsg2.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property NoticeMsg() As String
            Get
                Return ResourceManager.GetString("NoticeMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/upinfo.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property UpdateInfo() As String
            Get
                Return ResourceManager.GetString("UpdateInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/upinfosup.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property UpdateInfoSp() As String
            Get
                Return ResourceManager.GetString("UpdateInfoSp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/upver.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property UpdateVer() As String
            Get
                Return ResourceManager.GetString("UpdateVer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 https://cjhdevact.github.io/otherprojects/FlyEduDownloader/upversup.json 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property UpdateVerSp() As String
            Get
                Return ResourceManager.GetString("UpdateVerSp", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
